name: stepmotor
version: 1.0.0+1
publish_to: none
description: Step Dash Project
environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  webview_flutter: ^3.0.4
  url_launcher: ^6.3.0
  get: 4.6.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^1.1.4
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.2
  flutter_easyloading: ^3.0.5
  sp_util: ^2.0.3
  image_picker: ^1.1.2
  sliding_up_panel: ^2.0.0+1
  google_maps_flutter: ^2.9.0
  geocoder2: ^1.4.0
  location: ^7.0.0
  uuid: ^4.4.2
  flutter_polyline_points: ^1.0.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  flutter_swipe_button: ^2.1.3
  firebase_database: ^11.0.4
  midtrans_sdk: ^0.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo-mini.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Semibold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
