// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz7haYN9Cx8eC4IPVQ4l7buG4TNjYs9Ig',
    appId: '1:624770682842:web:189938b857dbe533a83ae3',
    messagingSenderId: '624770682842',
    projectId: 'flutterlaravel-e1b1c',
    authDomain: 'flutterlaravel-e1b1c.firebaseapp.com',
    storageBucket: 'flutterlaravel-e1b1c.appspot.com',
    measurementId: 'G-G16XFKC5YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ai-2BzoA2wTA8fz4r-ADpMBtobZpp4w',
    appId: '1:624770682842:android:ad59e50c038be1d1a83ae3',
    messagingSenderId: '624770682842',
    projectId: 'flutterlaravel-e1b1c',
    storageBucket: 'flutterlaravel-e1b1c.appspot.com',
    databaseURL:
        'https://flutterlaravel-e1b1c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSX-E9DYhlpNLDHRyAurL1uxfHPGYmfvc',
    appId: '1:624770682842:ios:0797b49a6be09aa8a83ae3',
    messagingSenderId: '624770682842',
    projectId: 'flutterlaravel-e1b1c',
    storageBucket: 'flutterlaravel-e1b1c.appspot.com',
    iosClientId:
        '624770682842-mipjs8jodd3r6jcgd41lk8ims93kpbtj.apps.googleusercontent.com',
    iosBundleId: 'com.ganangpriyambodo.stepmotor',
    databaseURL:
        'https://flutterlaravel-e1b1c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSX-E9DYhlpNLDHRyAurL1uxfHPGYmfvc',
    appId: '1:624770682842:ios:0797b49a6be09aa8a83ae3',
    messagingSenderId: '624770682842',
    projectId: 'flutterlaravel-e1b1c',
    storageBucket: 'flutterlaravel-e1b1c.appspot.com',
    iosClientId:
        '624770682842-mipjs8jodd3r6jcgd41lk8ims93kpbtj.apps.googleusercontent.com',
    iosBundleId: 'com.ganangpriyambodo.stepmotor',
    databaseURL:
        'https://flutterlaravel-e1b1c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz7haYN9Cx8eC4IPVQ4l7buG4TNjYs9Ig',
    appId: '1:624770682842:web:17bdb7efaab0a13da83ae3',
    messagingSenderId: '624770682842',
    projectId: 'flutterlaravel-e1b1c',
    authDomain: 'flutterlaravel-e1b1c.firebaseapp.com',
    storageBucket: 'flutterlaravel-e1b1c.appspot.com',
    measurementId: 'G-QSNS1DQ8SV',
    databaseURL:
        'https://flutterlaravel-e1b1c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
